"""user_lesson_progress_changed

Revision ID: 34e3e76fc541
Revises: b5e06817c93e
Create Date: 2026-05-26 18:21:58.601995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e3e76fc541'
down_revision: Union[str, Sequence[str], None] = 'b5e06817c93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_progress', sa.Column('exercises_ever_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'exercises_ever_completed')
    # ### end Alembic commands ###
