"""add cascade delete to user foreign keys

Revision ID: 38e79859bfd4
Revises: f51ceae8befa
Create Date: 2026-06-06 19:19:40.132741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e79859bfd4'
down_revision: Union[str, Sequence[str], None] = 'f51ceae8befa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_week_progress_user_id_fkey'), 'user_week_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_week_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_week_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_week_progress_user_id_fkey'), 'user_week_progress', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
