"""add_reading_texts_and_questions

Revision ID: 427520870529
Revises: 1ea8db8e549d
Create Date: 2026-06-25 18:24:38.163302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427520870529'
down_revision: Union[str, Sequence[str], None] = '1ea8db8e549d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hanzi', sa.Text(), nullable=False),
    sa.Column('content_pinyin', sa.Text(), nullable=True),
    sa.Column('content_translation', sa.Text(), nullable=True),
    sa.Column('hsk_level', sa.String(length=20), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reading_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('option_1', sa.String(length=255), nullable=False),
    sa.Column('option_2', sa.String(length=255), nullable=False),
    sa.Column('option_3', sa.String(length=255), nullable=False),
    sa.Column('option_4', sa.String(length=255), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('order_in_text', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['reading_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_questions_text_id'), 'reading_questions', ['text_id'], unique=False)
    op.create_table('user_reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['reading_texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'text_id', name='uq_user_reading_progress')
    )
    op.create_index(op.f('ix_user_reading_progress_text_id'), 'user_reading_progress', ['text_id'], unique=False)
    op.create_index(op.f('ix_user_reading_progress_user_id'), 'user_reading_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reading_progress_user_id'), table_name='user_reading_progress')
    op.drop_index(op.f('ix_user_reading_progress_text_id'), table_name='user_reading_progress')
    op.drop_table('user_reading_progress')
    op.drop_index(op.f('ix_reading_questions_text_id'), table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_table('reading_texts')
    # ### end Alembic commands ###
