"""simplify_user_reading_progress

Revision ID: 4e0f3379df50
Revises: 427520870529
Create Date: 2026-06-25 18:40:50.607311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0f3379df50'
down_revision: Union[str, Sequence[str], None] = '427520870529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reading_progress', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('user_reading_progress', 'score')
    op.drop_column('user_reading_progress', 'total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reading_progress', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_reading_progress', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_reading_progress', 'is_completed')
    # ### end Alembic commands ###
