"""add_exercises

Revision ID: 75de47318ed7
Revises: d0ac54bd3f65
Create Date: 2026-05-08 23:55:21.153627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75de47318ed7"
down_revision: Union[str, Sequence[str], None] = "d0ac54bd3f65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("question_description", sa.String(length=255), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("option_1", sa.String(length=255), nullable=False),
        sa.Column("option_2", sa.String(length=255), nullable=False),
        sa.Column("option_3", sa.String(length=255), nullable=False),
        sa.Column("option_4", sa.String(length=255), nullable=False),
        sa.Column("correct_answer", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("order_in_lesson", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercises")
    # ### end Alembic commands ###
