"""add indexes

Revision ID: b5e06817c93e
Revises: c95728af4ccb
Create Date: 2026-05-25 20:09:57.601471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e06817c93e'
down_revision: Union[str, Sequence[str], None] = 'c95728af4ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_exercise_progress_exercise_id'), 'user_exercise_progress', ['exercise_id'], unique=False)
    op.create_index('ix_user_exercise_progress_user_completed', 'user_exercise_progress', ['user_id', 'is_completed'], unique=False)
    op.create_index(op.f('ix_user_exercise_progress_user_id'), 'user_exercise_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_exercise_progress', 'user_exercise_progress', ['user_id', 'exercise_id'])
    op.create_index(op.f('ix_user_lesson_progress_lesson_id'), 'user_lesson_progress', ['lesson_id'], unique=False)
    op.create_index('ix_user_lesson_progress_user_completed', 'user_lesson_progress', ['user_id', 'is_completed'], unique=False)
    op.create_index(op.f('ix_user_lesson_progress_user_id'), 'user_lesson_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.create_index(op.f('ix_user_word_progress_next_review_at'), 'user_word_progress', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_index('ix_user_word_progress_user_review', 'user_word_progress', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_user_word_progress_word_id'), 'user_word_progress', ['word_id'], unique=False)
    op.create_unique_constraint('uq_user_word_progress', 'user_word_progress', ['user_id', 'word_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_word_progress', 'user_word_progress', type_='unique')
    op.drop_index(op.f('ix_user_word_progress_word_id'), table_name='user_word_progress')
    op.drop_index('ix_user_word_progress_user_review', table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_next_review_at'), table_name='user_word_progress')
    op.drop_constraint('uq_user_lesson_progress', 'user_lesson_progress', type_='unique')
    op.drop_index(op.f('ix_user_lesson_progress_user_id'), table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_user_completed', table_name='user_lesson_progress')
    op.drop_index(op.f('ix_user_lesson_progress_lesson_id'), table_name='user_lesson_progress')
    op.drop_constraint('uq_user_exercise_progress', 'user_exercise_progress', type_='unique')
    op.drop_index(op.f('ix_user_exercise_progress_user_id'), table_name='user_exercise_progress')
    op.drop_index('ix_user_exercise_progress_user_completed', table_name='user_exercise_progress')
    op.drop_index(op.f('ix_user_exercise_progress_exercise_id'), table_name='user_exercise_progress')
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
