"""add_idiom_model

Revision ID: d48ff2069bff
Revises: 38e79859bfd4
Create Date: 2026-06-07 14:33:41.419647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48ff2069bff'
down_revision: Union[str, Sequence[str], None] = '38e79859bfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idioms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hanzi', sa.String(length=20), nullable=False),
    sa.Column('pinyin', sa.String(length=100), nullable=False),
    sa.Column('translate', sa.String(length=500), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idioms')
    # ### end Alembic commands ###
