"""added is_started to model UserLessonProgress

Revision ID: e2c8032c9c8f
Revises: 21451a4231aa
Create Date: 2026-04-27 20:13:34.078774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c8032c9c8f'
down_revision: Union[str, Sequence[str], None] = '21451a4231aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_progress', sa.Column('is_started', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'is_started')
    # ### end Alembic commands ###
