"""add user_week_progress model

Revision ID: f41e8823a084
Revises: e2e74f665c91
Create Date: 2026-05-15 18:26:27.642415

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f41e8823a084"
down_revision: Union[str, Sequence[str], None] = "e2e74f665c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
