"""add_user_idiom_progress

Revision ID: f9c3c32aa529
Revises: d48ff2069bff
Create Date: 2026-06-07 16:37:39.538800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c3c32aa529'
down_revision: Union[str, Sequence[str], None] = 'd48ff2069bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_idiom_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idiom_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idiom_id'], ['idioms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idiom_id', name='uq_user_idiom_progress')
    )
    op.create_index(op.f('ix_user_idiom_progress_idiom_id'), 'user_idiom_progress', ['idiom_id'], unique=False)
    op.create_index(op.f('ix_user_idiom_progress_user_id'), 'user_idiom_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_idiom_progress_user_id'), table_name='user_idiom_progress')
    op.drop_index(op.f('ix_user_idiom_progress_idiom_id'), table_name='user_idiom_progress')
    op.drop_table('user_idiom_progress')
    # ### end Alembic commands ###
